---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[wma-activemq::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
